# Generated by Django 3.0.5 on 2021-04-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0002_auto_20210413_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1 day', 'Day 1'), ('2 days', 'Day 2'), ('3 days', 'Day 3'), ('4 days', 'Day 4'), ('5 days', 'Day 5'), ('6 days', 'Day 6'), ('1 week', 'Week 1'), ('2 weeks', 'Week 2'), ('3 weeks', 'Week 3'), ('1 month', 'Month')], max_length=255, verbose_name='rent period')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(choices=[(10, 'Discount 1'), (20, 'Discount 2'), (30, 'Discount 3'), (40, 'Discount 4'), (50, 'Discount 5'), (60, 'Discount 6'), (70, 'Discount 7'), (80, 'Discount 8'), (90, 'Discount 9'), (100, 'Discount 10')], verbose_name='discount')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_discount', to='product.Days')),
                ('dicounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_discount', to='product.Discount')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, choices=[('1 day', 'Day'), ('1 week', 'Week'), ('1 month', 'Month')], max_length=255, verbose_name='rent time')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/subcategories')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('condition', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('purchase_price', models.PositiveIntegerField(blank=True, null=True)),
                ('pledge', models.PositiveIntegerField(default=0)),
                ('inside_city', models.PositiveIntegerField(default=0, verbose_name='price within the city')),
                ('outside_city', models.PositiveIntegerField(default=0, verbose_name='price within the city')),
                ('delivery', models.PositiveIntegerField(default=0, verbose_name='delivery price')),
                ('pickup', models.CharField(blank=True, max_length=800, verbose_name='pickup address')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.Brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.Category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.City')),
                ('discount', models.ManyToManyField(blank=True, related_name='products', to='product.ItemDiscount')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.Subcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customuser.Client')),
            ],
        ),
    ]
