# Generated by Django 3.0.5 on 2021-04-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_auto_20210425_1743'),
        ('product', '0002_auto_20210413_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customuser.UserMode'),
        ),
    ]
