# Generated by Django 3.0.5 on 2021-04-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210425_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.PositiveIntegerField(default=0, verbose_name='price within the city')),
                ('outside_city', models.PositiveIntegerField(default=0, verbose_name='price outside the city')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='inside_city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='outside_city',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.Subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Delivery', verbose_name='delivery price'),
        ),
    ]
