# Generated by Django 3.0.5 on 2021-04-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_auto_20210425_2229'),
        ('product', '0004_auto_20210425_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='outside_city',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='price outside the city'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(limit_choices_to={'mode': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customuser.UserMode'),
        ),
    ]
