# Generated by Django 3.0.5 on 2021-04-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_auto_20210425_2229'),
        ('product', '0005_auto_20210425_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products')),
                ('owner', models.ForeignKey(limit_choices_to={'mode': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customuser.UserMode')),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='days',
            name='period',
            field=models.CharField(max_length=255, verbose_name='rent period'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.PositiveIntegerField(verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='products', to='product.ProductImage'),
        ),
    ]
