# Generated by Django 3.0.5 on 2021-05-06 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_auto_20210503_2052'),
        ('product', '0007_auto_20210501_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(limit_choices_to={'mode': '0'}, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='customuser.UserMode')),
            ],
        ),
    ]
