# Generated by Django 3.0.5 on 2021-04-25 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0005_auto_20210425_1743'),
        ('product', '0003_auto_20210425_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('contract', models.FileField(null=True, upload_to='contracts/')),
                ('status', models.CharField(choices=[('Rent Request', 'Rent Request'), ('Approval', 'Approval From Owner'), ('Contract signed', 'Contract Signed'), ('Money reserved', 'Money Reserved'), ('Rent Started', 'Rent Started'), ('Rent Finished', 'Rent Finished'), ('Rent aborted', 'Abort')], default='Rent Request', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_owner', to='customuser.UserMode')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_reciever', to='customuser.UserMode')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, owner=django.db.models.expressions.F('receiver')), name='receiver_and_owner_can_not_be_equal'),
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, start_date__gt=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('end_date'), '+', django.db.models.expressions.DurationValue(datetime.timedelta(days=1), output_field=models.DurationField()))), name='start_date_gt_end_date_plus_1_day'),
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, start_date__gt=datetime.datetime(2021, 4, 26, 17, 9, 12, 213478, tzinfo=utc)), name='start_date_can_be_the_next_day'),
        ),
    ]
