# Generated by Django 3.0.5 on 2021-04-25 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20210425_2205'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rent',
            name='start_date_can_be_the_next_day',
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, start_date__gt=datetime.datetime(2021, 4, 26, 19, 28, 58, 38711, tzinfo=utc)), name='start_date_can_be_the_next_day'),
        ),
    ]
