# Generated by Django 3.0.5 on 2021-04-30 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20210425_2229'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rent',
            name='start_date_can_be_the_next_day',
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('Rent Request', 'Rent Request'), ('Approval', 'Approval From Owner'), ('Contract signed', 'Contract Signed'), ('Rent Started', 'Rent Started'), ('Rent Finished', 'Rent Finished'), ('Rent aborted', 'Abort')], default='Rent Request', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, start_date__gt=datetime.datetime(2021, 5, 1, 19, 9, 5, 369858, tzinfo=utc)), name='start_date_can_be_the_next_day'),
        ),
    ]
