# Generated by Django 3.0.5 on 2021-05-06 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_auto_20210503_2119'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rent',
            name='start_date_can_be_the_next_day',
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, start_date__gt=datetime.datetime(2021, 5, 7, 20, 22, 51, 278642, tzinfo=utc)), name='start_date_can_be_the_next_day'),
        ),
    ]
