# Generated by Django 3.0.5 on 2021-04-05 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('flat_number', models.CharField(blank=True, max_length=255)),
                ('flor', models.IntegerField(blank=True)),
                ('entrance_number', models.CharField(blank=True, max_length=255)),
                ('intercome_code', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/avatar/')),
                ('birth_date', models.DateField(blank=True)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=False)),
                ('tg_notification', models.BooleanField(default=False)),
                ('phone_notification', models.BooleanField(default=False)),
                ('ws_notification', models.BooleanField(default=False)),
                ('address', models.ManyToManyField(blank=True, related_name='user', to='customuser.Address')),
                ('default_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customuser.City')),
            ],
        ),
    ]
