# Generated by Django 3.0.5 on 2021-04-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20210413_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('0', 'Get'), ('1', 'Give')], max_length=10)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.Client')),
            ],
            options={
                'unique_together': {('mode', 'customuser')},
            },
        ),
    ]
