# Generated by Django 3.0.5 on 2021-04-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(max_length=370)),
                ('comment_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_owner', to='customuser.UserMode')),
                ('comment_reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reciever', to='customuser.UserMode')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
