# Generated by Django 3.0.5 on 2021-04-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_auto_20210425_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermode',
            old_name='customuser',
            new_name='client',
        ),
        migrations.AlterUniqueTogether(
            name='usermode',
            unique_together={('mode', 'client')},
        ),
    ]
