# Generated by Django 3.0.5 on 2021-05-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_auto_20210425_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
