# Generated by Django 3.0.5 on 2021-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_auto_20210503_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
            preserve_default=False,
        ),
    ]
