# Generated by Django 3.0.5 on 2021-05-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0008_client_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_subscribed',
        ),
    ]
