# Generated by Django 3.0.5 on 2020-10-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(blank=True, null=True, verbose_name='request')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'reqests',
            },
        ),
    ]
