# Generated by Django 3.0.5 on 2021-05-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0008_client_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('month', 'Month'), ('six_month', 'Six Month'), ('year', 'Yead')], max_length=20)),
                ('subscribed_at', models.DateField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'mode': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customuser.UserMode')),
            ],
        ),
    ]
